import Head from "next/head";
import styles from "../styles/Home.module.css";
import Calls from "../components/Calls";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Making API Calls</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <Calls />
      </main>
    </div>
  );
}
